services:
  lite-cron:
    build:
      context: .
      dockerfile: Dockerfile
    image: lite-cron:latest
    container_name: lite-cron
    restart: on-failure:3
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - TIMEZONE=Asia/Shanghai
      - PYTHONPATH=/app
      - WEBUI=true
      - WEBUI_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/app/config.yml
      # - ./tasks:/app/tasks          # 内置脚本不建议挂载到主机 除非有明确需求需要修改
      - ./logs:/app/logs
      - ./data:/app/data              # 自定义脚本放到这里 同时修改config.yml中的脚本路径
    networks:
      - lite-cron

    healthcheck:
      test: ["CMD", "pgrep", "-f", "cron"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  lite-cron:
    name: lite-cron
    driver: bridge
